spring:
  application:
    name: mi-proyecto
  datasource:
    url: jdbc:mysql://localhost:3306/bicicletas_taller?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    com.primerproyecto: DEBUG
